import dayjs from "dayjs";

/* ================= REGION & NEIGHBORHOOD DATA ================= */
export const REGION_DATA: { region: string; neighborhoods: string[] }[] = [
  {
    region: "Abbotsford",
    neighborhoods: [
      "Abbotsford East",
      "Abbotsford West",
      "Aberdeen",
      "Bradner",
      "Central Abbotsford",
      "Matsqui",
      "Poplar",
      "Sumas Mountain",
      "Sumas Prairie",
    ],
  },
  {
    region: "Agassiz",
    neighborhoods: ["Agassiz", "Harrison Mills", "Mt Woodside"],
  },
  {
    region: "Bowen Island",
    neighborhoods: ["Bowen Island"],
  },
  {
    region: "Burnaby East",
    neighborhoods: ["East Burnaby", "Edmonds BE", "The Crest"],
  },
  {
    region: "Burnaby North",
    neighborhoods: [
      "Brentwood Park",
      "Capitol Hill BN",
      "Cariboo",
      "Central BN",
      "Forest Hills BN",
      "Government Road",
      "Montecito",
      "Oakdale",
      "Parkcrest",
      "Simon Fraser Hills",
      "Simon Fraser Univer.",
      "Sperling-Duthie",
      "Sullivan Heights",
      "Vancouver Heights",
      "Westridge BN",
      "Willingdon Heights",
    ],
  },
  {
    region: "Burnaby South",
    neighborhoods: [
      "Big Bend",
      "Buckingham Heights",
      "Burnaby Hospital",
      "Burnaby Lake",
      "Central Park BS",
      "Deer Lake",
      "Deer Lake Place",
      "Forest Glen BS",
      "Garden Village",
      "Greentree Village",
      "Highgate",
      "Metrotown",
      "Oaklands",
      "South Slope",
      "Suncrest",
      "Upper Deer Lake",
    ],
  },
  {
    region: "Chilliwack",
    neighborhoods: [
      "Chilliwack Downtown",
      "Chilliwack Mountain",
      "Chilliwack Proper East",
      "Chilliwack Proper South",
      "Chilliwack Proper West",
      "East Chilliwack",
      "Eastern Hillsides",
      "Fairfield Island",
      "Little Mountain",
      "Lower Landing",
      "Rosedale",
      "West Chilliwack",
    ],
  },
  {
    region: "Cloverdale",
    neighborhoods: ["Clayton", "Cloverdale BC", "Serpentine"],
  },
  {
    region: "Coquitlam",
    neighborhoods: [
      "Burke Mountain",
      "Canyon Springs",
      "Cape Horn",
      "Central Coquitlam",
      "Chineside",
      "Coquitlam East",
      "Coquitlam West",
      "Eagle Ridge CQ",
      "Harbour Chines",
      "Harbour Place",
      "Hockaday",
      "Maillardville",
      "Meadow Brook",
      "New Horizons",
      "North Coquitlam",
      "Park Ridge Estates",
      "Ranch Park",
      "River Springs",
      "Scott Creek",
      "Summitt View",
      "Upper Eagle Ridge",
      "Westwood Plateau",
      "Westwood Summit CQ",
    ],
  },
  {
    region: "Cultus Lake & Area",
    neighborhoods: [
      "Columbia Valley",
      "Cultus Lake East",
      "Cultus Lake North",
      "Cultus Lake South",
      "Vedder Mountain",
    ],
  },
  {
    region: "East Chilliwack",
    neighborhoods: ["Bridal Falls", "Popkum", "Rosedale"],
  },
  {
    region: "Fraser Canyon",
    neighborhoods: ["Fraser Canyon", "Lytton", "Yale – Dogwood Valley"],
  },
  {
    region: "FVREB Out of Town",
    neighborhoods: ["FVREB Out of Town"],
  },
  {
    region: "Harrison Lake",
    neighborhoods: ["Harrison Hot Springs", "Harrison Lake"],
  },
  {
    region: "Hope & Area",
    neighborhoods: ["Hope", "Kawkawa Lake", "Laidlaw", "Sunshine Valley"],
  },
  {
    region: "Islands-Van. & Gulf",
    neighborhoods: [
      "Gabriola Island",
      "Galiano Island",
      "Islands Other",
      "Mayne Island",
      "Pender Island",
      "Salt Spring Island",
      "Saturna Island",
    ],
  },
  {
    region: "Ladner",
    neighborhoods: [
      "Delta Manor",
      "East Delta",
      "Hawthorne",
      "Holly",
      "Ladner Elementary",
      "Ladner Rural",
      "Neilsen Grove",
      "Port Guichon",
      "Tilbury",
      "Westham Island",
    ],
  },
  {
    region: "Langley",
    neighborhoods: [
      "Aldergrove Langley",
      "Brookswood Langley",
      "Campbell Valley",
      "County Line Glen Valley",
      "Fort Langley",
      "Langley City",
      "Murrayville",
      "Otter District",
      "Salmon River",
      "Walnut Grove",
      "Willoughby Heights",
    ],
  },
  {
    region: "Maple Ridge",
    neighborhoods: [
      "Albion",
      "Cottonwood MR",
      "East Central",
      "Northeast",
      "North Maple Ridge",
      "Northwest Maple Ridge",
      "Silver Valley",
      "Southwest Maple Ridge",
      "Thornhill MR",
      "Websters Corners",
      "West Central",
      "Whonnock",
    ],
  },
  {
    region: "Mission",
    neighborhoods: [
      "Dewdney Deroche",
      "Durieu",
      "Hatzic",
      "Hemlock",
      "Lake Errock",
      "Mission BC",
      "Mission-West",
      "Stave Falls",
      "Steelhead",
    ],
  },
  {
    region: "N. Delta",
    neighborhoods: [
      "Annieville",
      "Nordel",
      "Scottsdale",
      "Sunshine Hills Woods",
    ],
  },
  {
    region: "New Westminster",
    neighborhoods: [
      "Connaught Heights",
      "Downtown NW",
      "Fraserview NW",
      "GlenBrooke North",
      "Moody Park",
      "North Arm",
      "Quay",
      "Queensborough",
      "Queens Park",
      "Sapperton",
      "The Heights NW",
      "Uptown NW",
      "West End NW",
    ],
  },
  {
    region: "North Surrey",
    neighborhoods: [
      "Bolivar Heights",
      "Bridgeview",
      "Cedar Hills",
      "Fraser Heights",
      "Guildford",
      "Port Kells",
      "Royal Heights",
      "Whalley",
    ],
  },
  {
    region: "North Vancouver",
    neighborhoods: [
      "Blueridge NV",
      "Boulevard",
      "Braemar",
      "Calverhall",
      "Canyon Heights NV",
      "Capilano NV",
      "Central Lonsdale",
      "Deep Cove",
      "Delbrook",
      "Dollarton",
      "Edgemont",
      "Forest Hills NV",
      "Grouse Woods",
      "Harbourside",
      "Indian Arm",
      "Indian River",
      "Lower Lonsdale",
      "Lynnmour",
      "Lynn Valley",
      "Mosquito Creek",
      "Norgate",
      "Northlands",
      "Pemberton Heights",
      "Pemberton NV",
      "Princess Park",
      "Queensbury",
      "Roche Point",
      "Seymour NV",
      "Tempe",
      "Upper Delbrook",
      "Upper Lonsdale",
      "Westlynn",
      "Westlynn Terrace",
      "Windsor Park NV",
      "Woodlands-Sunshine-Cascade",
    ],
  },
  {
    region: "Out of Town",
    neighborhoods: ["Out of Town"],
  },
  {
    region: "Pemberton",
    neighborhoods: [
      "Birken",
      "D'Arcy",
      "Devine",
      "Ivey Lake Estates",
      "Lillooet Lake",
      "Mount Currie",
      "Owl Ridge",
      "Pemberton",
      "Pemberton Meadows",
      "Poole Creek",
      "Walkerville Estates",
    ],
  },
  {
    region: "Pitt Meadows",
    neighborhoods: [
      "Central Meadows",
      "Mid Meadows",
      "North Meadows PI",
      "South Meadows",
      "West Meadows",
    ],
  },
  {
    region: "Port Coquitlam",
    neighborhoods: [
      "Birchland Manor",
      "Central Pt Coquitlam",
      "Citadel PQ",
      "Glenwood PQ",
      "Lincoln Park PQ",
      "Lower Mary Hill",
      "Mary Hill",
      "Oxford Heights",
      "Riverwood",
      "Woodland Acres PQ",
    ],
  },
  {
    region: "Port Moody",
    neighborhoods: [
      "Anmore",
      "Barber Street",
      "Belcarra",
      "College Park PM",
      "Glenayre",
      "Heritage Mountain",
      "Heritage Woods PM",
      "Mountain Meadows",
      "North Shore Pt Moody",
      "Port Moody Centre",
    ],
  },
  {
    region: "Richmond",
    neighborhoods: [
      "Boyd Park",
      "Bridgeport RI",
      "Brighouse",
      "Brighouse South",
      "Broadmoor",
      "East Cambie",
      "East Richmond",
      "Garden City",
      "Gilmore",
      "Granville",
      "Hamilton RI",
      "Ironwood",
      "Lackner",
      "McLennan",
      "McLennan North",
      "McNair",
      "Quilchena RI",
      "Riverdale RI",
      "Saunders",
      "Seafair",
      "Sea Island",
      "South Arm",
      "Steveston North",
      "Steveston South",
      "Steveston Village",
      "Terra Nova",
      "West Cambie",
      "Westwind",
      "Woodwards",
    ],
  },
  {
    region: "Sardis",
    neighborhoods: [
      "Chilliwack River Valley",
      "East Chilliwack",
      "Garrison Crossing",
      "Greendale",
      "Promontory",
      "Ryder Lake",
      "Sardis East Vedder",
      "Sardis South",
      "Sardis West Vedder",
      "Vedder Crossing",
    ],
  },
  {
    region: "South Surrey White Rock",
    neighborhoods: [
      "Crescent Bch Ocean Pk.",
      "Elgin Chantrell",
      "Grandview Surrey",
      "Hazelmere",
      "King George Corridor",
      "Morgan Creek",
      "Pacific Douglas",
      "Sunnyside Park Surrey",
      "White Rock",
    ],
  },
  {
    region: "Squamish",
    neighborhoods: [
      "Brackendale",
      "Brennan Center",
      "Britannia Beach",
      "Dentville",
      "Downtown SQ",
      "Garibaldi Estates",
      "Garibaldi Highlands",
      "Hospital Hill",
      "Northyards",
      "Paradise Valley",
      "Plateau",
      "Ring Creek",
      "Tantalus",
      "University Highlands",
      "Upper Squamish",
      "Valleycliffe",
    ],
  },
  {
    region: "Sunshine Coast",
    neighborhoods: [
      "Gambier Island",
      "Gibsons & Area",
      "Halfmn Bay Secret Cv Redroofs",
      "Keats Island",
      "Nelson Island",
      "Pender Harbour Egmont",
      "Roberts Creek",
      "Sechelt District",
    ],
  },
  {
    region: "Surrey",
    neighborhoods: [
      "Bear Creek Green Timbers",
      "East Newton",
      "Fleetwood Tynehead",
      "Panorama Ridge",
      "Queen Mary Park Surrey",
      "Sullivan Station",
      "West Newton",
    ],
  },
  {
    region: "Tsawwassen",
    neighborhoods: [
      "Beach Grove",
      "Boundary Beach",
      "Cliff Drive",
      "English Bluff",
      "Pebble Hill",
      "Tsawwassen Central",
      "Tsawwassen East",
      "Tsawwassen North",
    ],
  },
  {
    region: "Vancouver East",
    neighborhoods: [
      "Champlain Heights",
      "Collingwood VE",
      "Downtown VE",
      "Fraser VE",
      "Fraserview VE",
      "Grandview Woodland",
      "Hastings",
      "Hastings Sunrise",
      "Killarney VE",
      "Knight",
      "Main",
      "Mount Pleasant VE",
      "Renfrew Heights",
      "Renfrew VE",
      "South Marine",
      "South Vancouver",
      "Strathcona",
      "Victoria VE",
    ],
  },
  {
    region: "Vancouver West",
    neighborhoods: [
      "Arbutus",
      "Cambie",
      "Coal Harbour",
      "Downtown VW",
      "Dunbar",
      "Fairview VW",
      "False Creek",
      "Kerrisdale",
      "Kitsilano",
      "MacKenzie Heights",
      "Marpole",
      "Mount Pleasant VW",
      "Oakridge VW",
      "Point Grey",
      "Quilchena",
      "Shaughnessy",
      "South Cambie",
      "South Granville",
      "Southlands",
      "S.W. Marine",
      "University VW",
      "West End VW",
      "Yaletown",
    ],
  },
  {
    region: "West Vancouver",
    neighborhoods: [
      "Altamont",
      "Ambleside",
      "Bayridge",
      "British Properties",
      "Canterbury WV",
      "Caulfeild",
      "Cedardale",
      "Chartwell",
      "Chelsea Park",
      "Cypress",
      "Cypress Park Estates",
      "Deer Ridge WV",
      "Dundarave",
      "Eagle Harbour",
      "Eagleridge",
      "Furry Creek",
      "Gleneagles",
      "Glenmore",
      "Horseshoe Bay WV",
      "Howe Sound",
      "Lions Bay",
      "Olde Caulfeild",
      "Panorama Village",
      "Park Royal",
      "Passage Island",
      "Porteau Cove",
      "Queens",
      "Rockridge",
      "Sandy Cove",
      "Sentinel Hill",
      "Upper Caulfeild",
      "West Bay",
      "Westhill",
      "Westmount WV",
      "Whitby Estates",
      "Whytecliff",
    ],
  },
  {
    region: "Whistler",
    neighborhoods: [
      "Alpine Meadows",
      "Alta Vista",
      "Bayshores",
      "Benchlands",
      "Black Tusk - Pinecrest",
      "Blueberry Hill",
      "Brio",
      "Callaghan",
      "Cheakamus Crossing",
      "Emerald Estates",
      "Function Junction",
      "Green Lake Estates",
      "Nesters",
      "Nordic",
      "Rainbow",
      "Spring Creek",
      "Spruce Grove",
      "Upper Squamish",
      "WedgeWoods",
      "Westside",
      "Whistler Cay Estates",
      "Whistler Cay Heights",
      "Whistler Creek",
      "Whistler Village",
      "White Gold",
    ],
  },
  {
    region: "Yarrow",
    neighborhoods: ["Majuba Hill", "Yarrow"],
  },
];

/* ================= OTHER OPTIONS ================= */
export const YEAR_OPTIONS = [
  "Select Year",
  "1 Year",
  "2 Years",
  "3 Years",
  "4 Years",
  "5 Years",
  "6 Years",
  "7 Years",
  "8 Years",
];

export interface OptionGroup {
  category: string;
  items: string[];
}

export const getLastCompletedMonth = (): string => {
  return dayjs().subtract(1, "month").format("MMM");
};

export const getDataOptions = (lastMonth: string = getLastCompletedMonth()): OptionGroup[] => [
  {
    category: "Sold Price Charts",
    items: [
      "Sold Prices by Month",
      "Sold Prices by Month (Compare)",
      "Sold Prices per SqFt",
      "Sold Prices by Type YTD",
      "Sold Prices by Area YTD",
      `Sold Prices per SqFt every ${lastMonth}`,
      `Sold Prices by Type every ${lastMonth}`,
      `Sold Prices by Area every ${lastMonth}`,
    ],
  },
  {
    category: "Sold Count Charts",
    items: [
      "Sold Count by Month",
      "Sold Count by Month (Compare)",
      "Sold Count by Type YTD",
      "Sold Count by Area YTD",
      `Sold Count by Type every ${lastMonth}`,
      `Sold Count by Area every ${lastMonth}`,
    ],
  },
  {
    category: "Inventory Charts",
    items: [
      "Inventory Count by Month",
      "Months of Inventory",
    ],
  },
  {
    category: "Court-Ordered Charts",
    items: [
      "Court-Ordered Sold Count by Month",
      "Court-Ordered Inventory Count by Month",
    ],
  },
  {
    category: "Days on Market Charts",
    items: [
      "Median DOM by Month",
      `Median DOM every ${lastMonth}`,
    ],
  },
  {
    category: "Discount Charts",
    items: [
      "Median Discount from Orig. Price",
      `Median Discount every ${lastMonth}`,
    ],
  },
  {
    category: "Dollar Volume Charts",
    items: [
      "Sales Dollar Volume by Month",
      `Sales Dollar Volume every ${lastMonth}`,
    ],
  },
  {
    category: "Year-over-Year Charts",
    items: [
      "Y-over-Y Sold Count Change",
      "Y-over-Y Price Change",
    ],
  },
  {
    category: "Year-by-Year Comparison Charts",
    items: [
      "Sold Prices by Month Y-by-Y",
      "Sold Count by Month Y-by-Y",
      "Inventory Count by Month Y-by-Y",
    ],
  },
];

export const DATA_OPTIONS: OptionGroup[] = getDataOptions();

export const PROPERTY_OPTIONS = [
  "All Residential",
  "Detached",
  "Apartment",
  "Townhouse",
];

/* ================= REGION COORDINATES ================= */
export interface RegionCoordinate {
  region: string;
  latitude: number;
  longitude: number;
}

export const REGION_COORDINATES: RegionCoordinate[] = [
  {
    region: "Abbotsford",
    latitude: 49.0522,
    longitude: -122.3292,
  },
  {
    region: "Agassiz",
    latitude: 49.2386,
    longitude: -121.7681,
  },
  {
    region: "Bowen Island",
    latitude: 49.383,
    longitude: -123.35,
  },
  {
    region: "Burnaby East",
    latitude: 49.22,
    longitude: -122.95,
  },
  {
    region: "Burnaby North",
    latitude: 49.28,
    longitude: -122.965,
  },
  {
    region: "Burnaby South",
    latitude: 49.22,
    longitude: -122.98,
  },
  {
    region: "Chilliwack",
    latitude: 49.1579,
    longitude: -121.9515,
  },
  {
    region: "Cloverdale",
    latitude: 49.1044,
    longitude: -122.7294,
  },
  {
    region: "Coquitlam",
    latitude: 49.2838,
    longitude: -122.7932,
  },
  {
    region: "Cultus Lake & Area",
    latitude: 49.058,
    longitude: -121.984,
  },
  {
    region: "East Chilliwack",
    latitude: 49.19,
    longitude: -121.87,
  },
  {
    region: "Fraser Canyon",
    latitude: 50.35,
    longitude: -121.45,
  },
  {
    region: "FVREB Out of Town",
    latitude: 49.1,
    longitude: -122.6,
  },
  {
    region: "Harrison Lake",
    latitude: 49.302,
    longitude: -121.786,
  },
  {
    region: "Hope & Area",
    latitude: 49.3828,
    longitude: -121.4414,
  },
  {
    region: "Islands-Van. & Gulf",
    latitude: 49.35,
    longitude: -123.35,
  },
  {
    region: "Ladner",
    latitude: 49.089,
    longitude: -123.081,
  },
  {
    region: "Langley",
    latitude: 49.1011,
    longitude: -122.6588,
  },
  {
    region: "Maple Ridge",
    latitude: 49.2194,
    longitude: -122.6019,
  },
  {
    region: "Mission",
    latitude: 49.132,
    longitude: -122.311,
  },
  {
    region: "N. Delta",
    latitude: 49.15,
    longitude: -122.91,
  },
  {
    region: "New Westminster",
    latitude: 49.2057,
    longitude: -122.911,
  },
  {
    region: "North Surrey",
    latitude: 49.19,
    longitude: -122.83,
  },
  {
    region: "North Vancouver",
    latitude: 49.32,
    longitude: -123.072,
  },
  {
    region: "Out of Town",
    latitude: 49.1,
    longitude: -122.6,
  },
  {
    region: "Pemberton",
    latitude: 50.323,
    longitude: -122.807,
  },
  {
    region: "Pitt Meadows",
    latitude: 49.232,
    longitude: -122.689,
  },
  {
    region: "Port Coquitlam",
    latitude: 49.262,
    longitude: -122.781,
  },
  {
    region: "Port Moody",
    latitude: 49.283,
    longitude: -122.831,
  },
  {
    region: "Richmond",
    latitude: 49.1633,
    longitude: -123.1366,
  },
  {
    region: "Sardis",
    latitude: 49.119,
    longitude: -121.943,
  },
  {
    region: "South Surrey White Rock",
    latitude: 49.035,
    longitude: -122.81,
  },
  {
    region: "Squamish",
    latitude: 49.7016,
    longitude: -123.1558,
  },
  {
    region: "Sunshine Coast",
    latitude: 49.47,
    longitude: -123.75,
  },
  {
    region: "Surrey",
    latitude: 49.1913,
    longitude: -122.8491,
  },
  {
    region: "Tsawwassen",
    latitude: 49.0167,
    longitude: -123.0833,
  },
  {
    region: "Vancouver East",
    latitude: 49.255,
    longitude: -123.075,
  },
  {
    region: "Vancouver West",
    latitude: 49.24,
    longitude: -123.145,
  },
  {
    region: "West Vancouver",
    latitude: 49.327,
    longitude: -123.16,
  },
  {
    region: "Whistler",
    latitude: 50.1163,
    longitude: -122.9574,
  },
  {
    region: "Yarrow",
    latitude: 49.092,
    longitude: -121.862,
  },
];